apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: varuhinja
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: varuhinja
    newName: rg.fr-par.scw.cloud/djnd/varuhinja
    newTag: 'ccab7695570a4e7f10c1b17424ddade448a61ff5'
